name: SE333_Security
on: 
  push:
    branches: 
      - feature

jobs:
  SE333_SECURITY_JOB:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout repository
           uses: actions/checkout@v4

       # Initializes CodeQL tools and creates a codebase for analysis.
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v3
           with:
             languages: java
             dependency-caching: true




