name: SE333_CI
on: 
  push:
    branches: 
      - feature

jobs: 
  SE333_CI_JOB:
     runs-on: ubuntu-latest
     steps:
       - name: checkout-repo
         uses: actions/checkout@v4

       - name: setupJava
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
           cache: maven

       - name: Install Linter
         run: sudo apt-get install -y checkstyle

       - name: Run Checkstyle
         run: mvn checkstyle:check checkstyle.failOnViolation=false

       - name: Run Maven
         run: mvn test


