name: SE333_Security
on: 
  push:
    branches: 
      - feature

jobs:
  SE333_SECURITY_JOB:
     runs-on: ubuntu-latest
     permissions:
       security-events: write
       actions: read
       contents: read

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Initialize CodeQL
         uses: github/codeql-action/init@v3
         with:
           languages: java
           build-mode: manual  # Manual mode to control Maven build

       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '21'  # Adjust based on your project
           cache: maven

       - name: Build with Maven
         run: mvn clean install -DskipTests  # Skips tests for faster analysis

       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3

       - name: Upload CodeQL SARIF Report
         uses: github/codeql-action/upload-sarif@v3
         with:
              sarif_file: results.sarif  # Name of the artifact
              category: codeql-result


