name: SE333_Security
on: 
  push:
    branches: 
      - feature

jobs: 
  SE333Job:
     runs-on: ubuntu-latest
     steps:
       - name: checkout-repo
         uses: actions/checkout@v4

       - name: Intialize CodeQL
         uses: github/codeql-action/init@v3

       - name: Autobuild
         uses: github/codeql-action/autobuild@v3

       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3




