name: SE333_Security
on: 
  push:
    branches: 
      - feature

jobs:
  SE333_SECURITY_JOB:
     runs-on: ubuntu-latest
     steps:
       - name: checkout-repo
         uses: actions/checkout@v4

       - name: setupJava
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           architecture: x64
           cache: maven
       - name: run maven
         run: mvn package

       - name: Intialize CodeQL
         uses: github/codeql-action/init@v3

       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3




